config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  
  resources :collections do
  	resources :coins 
    member do
      scope module: "collection" do
      resources :toggle_coins, param: :toggle_coin_id
      end
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_and_belongs_to_many :coins
  belongs_to :user
  validates :currency, presence: true, uniqueness: true
  validate :collection_validator

  def id_validation?
  	user_id == user&.id 
  end
  	
  def collection_validator
  	errors.add(:user_id, "not the user of this collection") unless id_validation?
  end

  def my_owner_username
  	self.user.username
  end
end

app/controllers/collection/toggle_coins_controller.rb
class Collection::ToggleCoinsController < ApplicationController
	
	def destroy
		@collection = Collection.find(params[:id])
		@coin = Coin.find(params[:toggle_coin_id])
		if @collection.coins.include?(@coin)
			@collection.coins.delete(@coin)
			respond_to do |format| 
				#format.html {redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.'}
				format.js
			end
		else
			redirect_to collection_coins_path(@collection), notice: 'Coin unable to be delated from the collection.'
		end

	end

	def update
    @collection = Collection.find(params[:id])
    @coin = Coin.find(params[:toggle_coin_id])
    if @collection.coins.include?(@coin)
    	redirect_to collection_coins_path(@collection), notice: 'Unable to successfully update.' 
  	else
	    @collection.coins << @coin
	    respond_to do |format| 
	    	#format.html {redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.' }
	    	format.js
  		end
  	end
	end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /collections
  # GET /collections.json
  def index
    if current_user.admin?
      @collections = Collection.all
    else
      @collections = Collection.where(user_id: current_user.id) 
    end
    authorize @collections
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    authorize @collection
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    authorize @collection
    if @collection.valid? && @collection.id_validation? && Collection.exists?(@collection.id) == false
      respond_to do |format|
        if @collection.save 
          format.html { redirect_to collections_path, notice: 'Collection was successfully created.' }
          format.js
        else
          format.html { render :new }
          format.js
        end
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
      authorize @collection
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:currency, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: collection, local: true) do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :currency%>
    <%= form.text_field :currency, id: :collection_currency %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/_form.html.slim
= form_with(model: collection, local: true) do |form| 
  - if collection.errors.any? 
    div id="error_explanation"
      h2 
        = pluralize(collection.errors.count, "error") 
      ul
      - collection.errors.full_messages.each do |message| 
        li 
          = message 
  div.field
    b
      = form.label :currency
      |  
      = form.text_field :currency, id: :collection_currency 
  div.actions
    = form.submit 

app/views/collections/edit.html.slim
body style="background-color:#d5dadc"
	h1.formattitlecollection Editing Collection
	div.formatcrudcollection
		= render 'form', collection: @collection 
		= link_to 'Show ', collection_path(@collection), {:style => 'color:#00a7cc'} 
		br
		= link_to 'Back', collections_path, {:style => 'color:#00a7cc'} 

app/views/collections/index.html.slim
h1.formattitlecollection Collections  
body style="background-color:#d5dadc"
  div.container
    div.row
      div.col-lg-12
        table.table align="center"         
          tr    
            td class="formatsubheadercollection" CURRENCY 
            td class="formatsubheadercollection" OPTIONS 
            - if current_user.admin? 
              td class="formatsubheadercollection" COLLECTIONIST 
          - @collections.each do |collection|  
            tr
              td class="formatcontentcollection"
                = collection.currency 
              td class="formatcontentcollection"
                = link_to 'My coins ', collection_coins_path(collection)
                = link_to 'Edit ', edit_collection_path(collection)
                = link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } 
              td class="formatcontentcollection"
                = collection.my_owner_username 
            
    div.row            
      div.col-lg-12
        p class="logcontentcollection"
          = link_to 'New Collection', new_collection_path, class: 'linkcolor' 
        - if user_signed_in? 
          p class="logcontentcollection"
            = link_to 'Logout', destroy_user_session_path, method: :delete,  class: 'linkcolor'  
        - if current_user.admin? 
          p class="logcontentcollection" 
            = link_to 'Users',  users_path

app/views/collections/new.html.slim
h1.formattitlecollection New Collection
body.formatcrudcollection	 style="background-color:#d5dadc"
	= render 'form', collection: @collection 
	= link_to 'Back', root_path, {:style => 'color:#00a7cc'} 

app/views/collections/show.html.slim
h1.formattitlecollection My collections
body.formatcrudcollection style="background-color:#d5dadc"
	b
 		= @collection.currency 
 	br
 	= link_to 'Back', collections_path, {:style => 'color:#00a7cc'} 