config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  
  resources :collections do
  	resources :coins 
    member do
      scope module: "collection" do
      resources :toggle_coins, param: :toggle_coin_id
      end
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_and_belongs_to_many :coins
  belongs_to :user
  validates :currency, presence: true, uniqueness: true
  validate :collection_validator

  def id_validation?
  	user_id == user&.id 
  end
  	
  def collection_validator
  	errors.add(:user_id, "not the user of this collection") unless id_validation?
  end

  def my_owner_username
  	self.user.username
  end
end

app/controllers/collection/toggle_coins_controller.rb
class Collection::ToggleCoinsController < ApplicationController
	
	def destroy
		@collection = Collection.find(params[:id])
		@coin = Coin.find(params[:toggle_coin_id])
		if @collection.coins.include?(@coin)
			@collection.coins.delete(@coin)
			respond_to do |format| 
				#format.html {redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.'}
				format.js
			end
		else
			redirect_to collection_coins_path(@collection), notice: 'Coin unable to be delated from the collection.'
		end

	end

	def update
    @collection = Collection.find(params[:id])
    @coin = Coin.find(params[:toggle_coin_id])
    if @collection.coins.include?(@coin)
    	redirect_to collection_coins_path(@collection), notice: 'Unable to successfully update.' 
  	else
	    @collection.coins << @coin
	    respond_to do |format| 
	    	#format.html {redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.' }
	    	format.js
  		end
  	end
	end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /collections
  # GET /collections.json
  def index
    if current_user.admin?
      @collections = Collection.all
    else
      @collections = Collection.where(user_id: current_user.id) 
    end
    authorize @collections
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
    authorize @collection
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    authorize @collection
    if @collection.valid? && @collection.id_validation? && Collection.exists?(@collection.id) == false
      respond_to do |format|
        if @collection.save 
          format.html { redirect_to collections_path, notice: 'Collection was successfully created.' }
          format.js
        else
          format.html { render :new }
          format.js
        end
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_coins_path(@collection), notice: 'Collection was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
      authorize @collection
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:currency, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collection/toggle_coins/_counter_coin_from_collection.html.slim
= counter  

app/views/collection/toggle_coins/_remove_coin_from_collection.html.slim
head
	script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"



= link_to toggle_coin_path(collection.id, coin), remote: true, method: :delete do
	i class="far fa-times-circle" color="#ff1a1a"

app/views/collection/toggle_coins/_sumcounter_coin_from_collection.html.slim
= sumcounter 

app/views/collection/toggle_coins/_update_coin_from_collection.html.slim
head
	script src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"
	
= link_to toggle_coin_path(collection.id, coin), remote: true, method: :put do 
	i class="fas fa-check" color="#1aff1a"

app/views/collection/toggle_coins/counter.js.erb
$('#counter-form').html("<%= j(render 'collection/toggle_coins/counter_coin_from_collection', counter: counter) %>");

app/views/collection/toggle_coins/destroy.js.erb
$('#destroy-form-<%=@coin.id%>').html("<%= j(render 'collection/toggle_coins/update_coin_from_collection', collection: @collection, coin: @coin) %>");

app/views/collection/toggle_coins/sumcounter.js.erb
$('#sumcounter-form').html("<%= j(render 'collection/toggle_coins/sumcounter_coin_from_collection', sumcounter: sumcounter) %>");

app/views/collection/toggle_coins/update.js.erb
$('#update-form-<%=@coin.id%>').html("<%= escape_javascript(render partial: 'collection/toggle_coins/remove_coin_from_collection', locals: {collection: @collection, coin: @coin}) %>");