config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  
  resources :collections do
  	resources :coins 
    member do
      scope module: "collection" do
      resources :toggle_coins, param: :toggle_coin_id
      end
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	
	has_many :collections
  
  after_initialize :set_default_role, :if => :new_record?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :authentication_keys => [:login]
  validates :username, uniqueness: true

  enum roles: {
  	collectionist: 0,
  	admin: 1
  }

  def my_user_name
    self.username
  end

  def set_default_role
    self.roles ||= :user
  end

  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username || self.email
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    if conditions[:username].nil?
	      where(conditions).first
	    else
	      where(username: conditions[:username]).first
	    end
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	def index
		if current_user.admin?
			@q = User.ransack(params[:q])
  		@users = @q.result(distinct: true)
		end
	end

	def show
  end

  # GET /collections/new
  def new
		if current_user.admin?
    @user = User.new
		end
  end

  # GET /collections/1/edit
  def edit
  end

  def update
    if current_user.admin?
	    	respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to @user, notice: 'User was successfully updated.' }
	      else
	        format.html { render :edit }
	      end
	    end
	  end  
  end

	def destroy
		if current_user.admin?
			@user.destroy
    	respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    	end
    end
	end

  private

    def set_user
    	@user = User.find(params[:id])
    end
  # Never trust parameters from the scary internet, only allow the white list through.
	  def user_params
	    params.require(:user).permit(:email, :username)
	  end
end

app/views/users/_form.html.slim
= form_with(model: user, local: true) do |form| 
  - if user.errors.any? 
    div id="error_explanation"
      h2= pluralize(user.errors.count, "error") 
      ul
      - user.errors.full_messages.each do |message| 
        li= message 

  div class="field"
    b
      = form.label :email 
      = form.text_field :email   

  div class="field"
    b
      = form.label :username 
      = form.text_field :username 

  div class="field"
    b
      = form.label :roles 
      = form.text_field :roles 
  
  div class="actions"
    = form.submit 
  
 

app/views/users/edit.html.slim
h1.formattitlecollection Editing User
body style="background-color:#d5dadc"
	div.formatcrudcollection
		= render 'form', user: @user 
		= link_to 'Show', user_path(@user) 
		br
		= link_to 'Back', users_path

app/views/users/index.html.slim
h1.formattitlecollection Users
body style="background-color:#d5dadc"
  div.formatcrudcollection
    = search_form_for @q do |user| 
      b
        = user.label :username
      br
      = user.search_field :username_cont 
      br
      = user.submit 

      table
        thead
          tr
            th
            br
            b
              = sort_link(@q, :username) 
          
        tbody
          - @users.each do |user|     
            td
            b
              |  
              = user.my_user_name
            br
            = link_to 'Edit ', edit_user_path(user)
            = link_to 'Back', collections_path
      

app/views/users/new.html.slim
h1.formattitlecollection New User
body style="background-color:#d5dadc"
	div.formatcrudcollection
		= render 'form', collection: @collection 
		= link_to 'Back', root_path, {:style => 'color:#00a7cc'} 

app/views/users/show.html.slim
p id="notice" = notice 
h1.formattitlecollection User
body style="background-color:#d5dadc"
	div.formatcrudcollection
		b
	 		= @user.email
	 		br
	 		= @user.username
	 	br
		= link_to 'Back', users_path