config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users
  
  resources :collections do
  	resources :coins 
    member do
      scope module: "collection" do
      resources :toggle_coins, param: :toggle_coin_id
      end
    end
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coin.rb
class Coin < ApplicationRecord
  has_and_belongs_to_many :collections
  validates :year, presence: true
  validates :country, presence: true
  validates :value, presence: true    
  validate :year_validator

  def self.introduced_euro(country) 
    country_introduction_years = {
      "andorra": 2015,
      "austria": 1999,
      "belgium": 1999, 
      "ciprus": 2008, 
      "estonia": 2011, 
      "finland": 1999, 
      "france": 1999, 
      "germany": 1999, 
      "greece": 2001, 
      "ireland": 1999, 
      "italy": 1999, 
      "latvia": 2014, 
      "lithuania": 2015, 
      "luxemburg": 1999, 
      "malta": 2007, 
      "monaco": 1999,
      "netherlands": 1999,  
      "portugal": 1999, 
      "sanmarino": 1999,
      "slovakia": 2008, 
      "slovenia": 2007, 
      "spain": 1999, 
      "vatican": 1999
    }
    country_introduction_years.each do |k, v| 
      if country.eql?(k.to_s) 
        return v 
     end
    end
  end
  
  ANDORRA = 0 
  AUSTRIA = 1 
  BELGIUM = 2
  CIPRUS = 3
  ESTONIA = 4 
  FINLAND = 5 
  FRANCE = 6
  GERMANY = 7 
  GREECE = 8  
  IRELAND = 9 
  ITALY = 10 
  LATVIA = 11 
  LITHUANIA = 12
  LUXEMBURG = 13 
  MALTA = 14 
  MONACO = 15 
  NETHERLANDS = 16 
  PORTUGAL = 17
  SANMARINO = 18 
  SLOVAKIA = 19 
  SLOVENIA = 20 
  SPAIN = 21 
  VATICAN = 22 
  

  enum country: {

    andorra: ANDORRA,
    austria: AUSTRIA,
    belgium: BELGIUM, 
    ciprus: CIPRUS, 
    estonia: ESTONIA, 
    finland: FINLAND, 
    france: FRANCE, 
    germany: GERMANY, 
    greece: GREECE, 
    ireland: IRELAND, 
    italy: ITALY, 
    latvia: LATVIA, 
    lithuania: LITHUANIA, 
    luxemburg: LUXEMBURG, 
    malta: MALTA, 
    monaco: MONACO,
    netherlands: NETHERLANDS, 
    portugal: PORTUGAL, 
    sanmarino: SANMARINO,
    slovakia: SLOVAKIA, 
    slovenia: SLOVENIA, 
    spain: SPAIN, 
    vatican: VATICAN

  }


  ONECENT = 0.01 
  TWOCENT = 0.02
  FIVECENT = 0.05
  TENCENT = 0.1
  TWENTYCENT = 0.2
  FIFTYCENT = 0.5
  ONEEURO = 1
  TWOEURO = 2

  enum value: {
    onecent: ONECENT,
    twocent: TWOCENT,
    fivecent: FIVECENT,
    tencent: TENCENT,
    twentycent: TWENTYCENT,
    fiftycent: FIFTYCENT,
    oneeuro: ONEEURO,
    twoeuro: TWOEURO
  }

  def self.get_coin_value(val) 
    values.each { |k,v| if val.eql?(k)
        return v
      end
    }
  end

  def year_is_valid?
    year && year >= Coin.introduced_euro(country) && year <= Date.current.year
  end

  def year_validator
    errors.add(:year, "year is not permitted") unless year_is_valid?
  end

  def select_options_tag(name='',select_options={},options={})
    #set selected from value
    selected = ''
    unless options[:value].blank?
      selected = options[:value]
      options.delete(:value)
    end
    select_tag(name,options_for_select(select_options,selected),options)
  end
end
  

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_collection, only: [:new, :create, :update, :edit, :destroy, :index]

  # GET /coins
  # GET /coins.json
  def index
    if params[:country].blank? 
      params[:country] = "andorra"
    end
    @coins = @collection.coins
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
    authorize @coin
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)
    authorize @coin
    if current_user.admin? && @coin.year_is_valid? && Coin.exists?(@coin.id) == false
      respond_to do |format|
        if @coin.save
          format.html { redirect_to collection_coins_path, notice: 'Coin was successfully created.' }
          format.js
        else
          format.html { render :new }
          format.js
        end
      end
    else
      redirect_to collection_coins_path, notice: 'Unable to create coin, it does not apply to the data needed'
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params) && @coin.year_is_valid?
        format.html { redirect_to collection_coins_path, notice: 'Coin was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to collection_coins_path(@collection), notice: 'Coin was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:year, :country, :value)
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.slim
= form_with(model: [collection, coin], remote: true) do |form| 
  - if coin.errors.any? 
    div id="error_explanation"
      h2= pluralize(coin.errors.count, "error") 

      ul
       coin.errors.full_messages.each do |message| 
        li
        = message 
            
  
  
  div class="field"
    b
      = form.label :year 
      |  
      = form.text_field :year, id: :coin_year 


  div class="field"  
    b
      = form.label :country 
      |  
      = select("coin", "country", Coin.countries.keys.map{|x| x.capitalize}) 


  div class="field"
    b
      = form.label :value 
      |  
      = select("coin", "value", Coin.values.keys) 


  div class="actions"
    = form.submit 

app/views/coins/edit.html.slim
h1.formattitlecollection Editing Coin
body style="background-color:#d5dadc"
	div.formatcrudecollection
		= render 'form', coin: @coin, collection: @collection

		= link_to 'Show', collection_coin_path(@collection, @coin) 
		= link_to 'Back', collection_coins_path(@collection) 

app/views/coins/index.html.slim
p id="notice" = notice 
h1.formattitlecollection Coins
body style="background-color:#d5dadc"

  div.container
    div.row
      div.col-lg-12
        table class="table table-bordered"
          tr
            th scope="col"
              form url = "collection_coins_path(@collection)" method = "GET" 
                = select_tag :country, options_for_select(Coin.countries.keys.map{|x| x.capitalize}) 
                |  
                button type="submit" Show
             
            th scope="col" Year   
            th scope="col"  2   
            th scope="col"  1   
            th scope="col"  0,5  
            th scope="col"  0,2  
            th scope="col"  0,1  
            th scope="col"  0,05  
            th scope="col"  0,02  
            th scope="col"  0,01  
            th scope="col" Total
            th scope="col" Amount
        
          tbody
            - for i in Coin.introduced_euro(params[:country].camelize(:lower))..Date.current.year 
              tr
                td 
                  b
                    = params[:country].upcase  
                td 
                  b
                    = i 
                - sumcounter = 0 
                - counter = 0 
                - Coin.where(country: params[:country].camelize(:lower), year: i).order(year: :asc, value: :desc).each do |coin|   
                  td 
                    - if @coins.include?(coin) 
                      div id="destroy-form-#{coin.id}"
                        = render 'collection/toggle_coins/remove_coin_from_collection', collection: @collection, coin: coin  
                        - sumcounter += Coin.get_coin_value(coin.value)
                        - counter += 1 

                    - else 
                      div id="update-form-#{coin.id}"
                        = render 'collection/toggle_coins/update_coin_from_collection', collection: @collection, coin: coin          
                     
                td  
                  div id="counter-form"
                    = render 'collection/toggle_coins/counter_coin_from_collection', counter: counter
                 
                td  
                  div id="sumcounter-form"
                    = render 'collection/toggle_coins/sumcounter_coin_from_collection', sumcounter: sumcounter 
    div.row
      div.col-lg-2              
        = link_to 'New Coin', new_collection_coin_path(@collection), { class: ' linkcolor'}
        br
        = link_to 'Back', collections_path

app/views/coins/new.html.slim
h1.formattitlecollection New Coin
body style="background-color:#d5dadc"
	div.formatcrudcollection
		= render 'form', collection: @collection, coin: @coin 

		= link_to 'Back', collection_coins_path 

app/views/coins/new.js.erb
$('#new-collection-coin').html("<%= j(render 'new_coin_in_collection', collection: @collection, coin: @coi)n %>");

app/views/coins/show.html.slim
p id="notice" notice 
body style="background-color:#d5dadc"

  strong Year:/strong
  = @coin.year 



  strong Country:/strong
  = @coin.country 



  strong Value:/strong
  = @coin.value 


	= link_to 'Back', collection_coins_path 